apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-dev-tools
  name: web-dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dev-tools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-dev-tools
    spec:
      containers:
      - image: seijikohara/web-dev-tools
        name: web-dev-tools
        resources: {}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 20000
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 20000
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: web-dev-tools
status: {}
