apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-dev-tools
  name: web-dev-tools
spec:
  ports:
  - name: 80-20000
    port: 80
    protocol: TCP
    targetPort: 20000
  selector:
    app: web-dev-tools
  type: ClusterIP
status:
  loadBalancer: {}
